# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
    - trailing_comma
    - identifier_name
    - line_length
    - cyclomatic_complexity
    - function_parameter_count
    - function_body_length
    - file_length

opt_in_rules: # some rules are turned off by default, so you need to opt-in
    - indentation_width

included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.

reporter: "github-actions-logging" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
