name: DocC

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2

    - run: swift package --allow-writing-to-directory ./docs generate-documentation --target TMDBSwift --disable-indexing --output-path ./docs --transform-for-static-hosting --hosting-base-path TheMovieDatabaseSwiftWrapper
    
    - name: Configure git
      run: |
        git config --global user.email "no-reply@tmdbswiftwrapper.com"
        git config --global user.name "tmdb-bot"
        
    - name: Commit Changes
      run: |
        git add docs/*
        git commit -m "Updating Documentation"
        git push origin master
