name: DocC

on:
  workflow_dispatch:

jobs:
  Publish:
    runs-on: macos-12
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.3.1.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - run: swift package --allow-writing-to-directory ./docs generate-documentation --target TMDBSwift --output-path ./docs --transform-for-static-hosting --hosting-base-path TMDBSwift
