name: DocC

on:
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5'
    
    - uses: fwcd/swift-docc-action@v1
      with:
        target: TMDBSwift
        output: ./docs
        hosting-base-path: http://dpearce.github.io/TheMovieDatabaseSwiftWrapper/
        disable-indexing: 'true'
        transform-for-static-hosting: 'true'
